export function getHtmlData (){
    return {
        type:"", // web(只用于PC端)|wap(只用于移动端)|(PC和移动端通用该值为空)|
        color:'蓝色', // 多个颜色用逗号分隔 目前取值项：红色,橙色,蓝色,绿色,棕色,黄色,紫色,粉色,黑色,青色,灰色
        effect:'static', // dynamic(动态)|static(静态)
        fileName:'nyb029.js', // 该文件的文件名
        styleWebCode:'.smalltext029{background: #eaf7ff;padding:.1333125rem 4%;margin: 24px 0;text-align:center;border-radius: 10px;position:relative;} .smalltext029:after,.smalltext029:before{content:"";width: 18px;height: 18px;background:#fff;border-radius:50%;box-shadow: -1px 1px 4px #9fb6dc inset;position:absolute;left: 20px;top: 20px;} .smalltext029:after{left:auto;right: 20px;} .smalltext029 p{text-align:left} .smalltext029 .p1{background:#94c6f7;display:inline-block;padding: 3px 3%;font-size: 18px;color:#fff;position:relative;} .smalltext029 .p1:before{content:"";width:100%;height: 3px;background:#94c6f7;display:block;position:absolute;left:0;bottom: -6px;} .smalltext029 .p1:after{content:"";width:100%;height: 25px;background:url(../images/insidestyle/smalltext029-tb.png) center no-repeat;background-size: 15px;display:block;position:absolute;left:0;bottom: -40px;} .smalltext029 .p2{color:#4e79bf;text-align:center;} .smalltext029 .p1 strong{font-size: 20px;color:#fff!important;}', // PC端样式
        styleWapCode:'.smalltext029{background: #eaf7ff;padding:.1333125rem 4%;margin:.4rem 0;text-align:center;border-radius:.16rem;position:relative;} .smalltext029:after,.smalltext029:before{content:"";width:.28125rem;height:.28125rem;background:#fff;border-radius:50%;box-shadow:-1px 1px .0666875rem #9fb6dc inset;position:absolute;left:.32rem;top:.4rem} .smalltext029:after{left:auto;right:.32rem} .smalltext029 p{text-align:left} .smalltext029 .p1{background:#94c6f7;display:inline-block;padding:0 5%;color:#fff;position:relative} .smalltext029 .p1:before{content:"";width:100%;height:.05333125rem;background:#94c6f7;display:block;position:absolute;left:0;bottom:-.09375rem} .smalltext029 .p1:after{content:"";width:100%;height:.3333125rem;background:url(../images/insidestyle/smalltext029-tb.png) center no-repeat;background-size:.28125rem;display:block;position:absolute;left:0;bottom:-.73321875rem} ', // 移动端样式
        htmlString:'<div class="smalltext029"><p class="p1"><strong>标题标题</strong></p><p>正文正文</p></div>'
    };
}