export function getHtmlData (){
    return {
        type:"", // web(只用于PC端)|wap(只用于移动端)|(PC和移动端通用该值为空)|
        color:'蓝色', // 多个颜色用逗号分隔 目前取值项：红色,橙色,蓝色,绿色,棕色,黄色,紫色,粉色,黑色,青色,灰色
        effect:'static', // dynamic(动态)|static(静态)
        fileName:'nyb024.js', // 该文件的文件名
        styleWebCode:'.smalltext024{background:#f2faff;padding:1px 30px 20px;position:relative;max-width:800px;margin-left:auto;margin-right:auto;margin-top:60px;}.smalltext024 strong{width:-webkit-fit-content;width:-moz-fit-content;width:fit-content;display:block;background:#fff;border:2px solid #4d96d8;color:#4d96d8;font-weight:700;line-height:30px;text-align:center;position:relative;margin:-30px auto 0px;font-size:20px;padding:10px 20px;}.smalltext024 strong span{background:#fff;font-size:25px;font-weight:bold;line-height:1;position:absolute;left:15px;top:-15px;text-align:center;padding:2px 10px;}.smalltext024 strong span:before{content:"";width:12px;height:12px;background:#4d96d8;display:block;position:absolute;right:-12px;top:50%;margin-top:-6px;}.smalltext024 p{margin:15px 0px 0px 0px;}', // PC端样式
        styleWapCode:'.smalltext024{background:#f2faff;padding:0.01333rem 0.4rem 0.26667rem;position:relative;margin-top:0.93333rem;}.smalltext024 strong{width:-webkit-fit-content;width:-moz-fit-content;width:fit-content;display:block;background:#fff;border:2px solid #4d96d8;color:#4d96d8;font-weight:700;line-height:0.53333rem;text-align:center;position:relative;margin:-0.4rem auto 0px;font-size:0.42667rem;padding:0.13333rem 0.26667rem;}.smalltext024 strong span{background:#fff;font-size:0.33333rem;font-weight:bold;line-height:1;position:absolute;left:0.2rem;top:-0.2rem;text-align:center;padding:0.02667rem 0.13333rem;}.smalltext024 strong span:before{content:"";width:0.16rem;height:0.16rem;background:#4d96d8;display:block;position:absolute;right:-0.16rem;top:50%;margin-top:-0.08rem;}.smalltext024 p{margin:0.2rem 0rem 0rem 0rem;}', // 移动端样式
        htmlString:'<div class="smalltext024"><strong><span>1</span>标题标题标题标题</strong><p>正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文</p><p>正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文</p></div>'
    };
}