/*
 * @Author: your name
 * @Date: 2020-01-07 10:45:01
 * @LastEditTime: 2020-01-07 10:45:04
 * @LastEditors: your name
 * @Description: In User Settings Edit
 * @FilePath: \hx-editor\src\components\editorData\tableData\modules\nyb001.js
 */

export function getHtmlData (){
    return {
        type:"", // web(只用于PC端)|wap(只用于移动端)|(PC和移动端通用该值为空)|
        color:'红色,蓝色', // 多个颜色用逗号分隔 目前取值项：红色,橙色,蓝色,绿色,棕色,黄色,紫色,粉色,黑色,青色,灰色
        effect:'static', // dynamic(动态)|static(静态)
        align:'left', // left(左对齐)|center(居中对齐)|right(右对齐)        
        style:'icon', // icon(图标)|number(数字)|other(其他)
        fileName:'nyb001.js', // 该文件的文件名
        styleWebCode:'.smalltable001 { clear: both; margin: 20px 0px; background: url(../images/insidestyle/smalltableicon001.jpg) no-repeat center top #fff; background-size: 100% 100%; width: 100%; padding: 5px 60px 50px; box-sizing: border-box; } .smalltable001 .smalltable001tit { font-size: 26px !important; color: #fff !important; font-weight: bold; margin: 25px 0 25px !important; text-align: center; padding: 0px !important; background: none !important; } .smalltable001 .smalltable001tit:before { width: 82px; height: 21px; content: ""; display: inline-block; background: url(../images/insidestyle/smalltableicon002.png) no-repeat; position: static; margin-right: 15px; vertical-align: middle; } .smalltable001 .smalltable001tit:after { width: 82px; height: 21px; content: ""; display: inline-block; background: url(../images/insidestyle/smalltableicon003.png) no-repeat; position: static; margin-left: 15px; vertical-align: middle; } .smalltable001 .smalltable001box { border: 12px solid #fff;background: #fff; box-shadow: 0 0 30px rgba(44, 80, 179, 0.2); } .smalltable001 .smalltable001box table { margin: 0 auto; width: 100%; border-collapse: collapse; } .smalltable001 .smalltable001box table tr { border: 1px solid #000; } .smalltable001 .smalltable001box table tr:first-child td { background: #dee6ff } .smalltable001 .smalltable001box table tr:nth-child(even) td { background: #f7f7f7 } .smalltable001 .smalltable001box table td { padding: 15px 10px!important; word-break: break-all!important; border: 1px solid #000; text-align: center; font-size: 16px; } .smalltable001 .smalltable001box table td a { color: #6b86cf; text-decoration: underline; position: relative; } @media (max-width: 1760px) { .smalltable001 .smalltable001box table td { line-height: 36px; } } @media (max-width: 1600px) { .smalltable001 .smalltable001box table td { line-height: 32px; } .smalltable001 .smalltable001tit { font-size: 24px !important; } } @media (max-width: 1440px) { .smalltable001 .smalltable001box table td { font-size: 14px; line-height: 28px; padding: 10px 10px!important; } .smalltable001 .smalltable001tit { font-size: 22px !important; } } @media (max-width: 1280px) { .smalltable001 .smalltable001box table td { line-height: 24px; } .smalltable001 .smalltable001tit { font-size: 20px !important; } }', // PC端样式
        styleWapCode:'.smalltable001{clear:both;margin:.26667rem 0rem;background:url(../images/insidestyle/smalltableicon001.jpg) no-repeat center top #fff;background-size:100% 100%;width:100%;padding:.06667rem .26667rem .4rem;box-sizing:border-box}.smalltable001 .smalltable001tit{font-size:.4rem;margin-bottom:.4rem;color:#fff;font-weight:bold;margin:.33333rem 0rem;text-align:center;color:#fff;background:none;padding:0rem}.smalltable001 .smalltable001tit:before{width:1.09333rem;height:.28rem;content:"";display:inline-block;background:url(../images/insidestyle/smalltableicon002.png) no-repeat;position:static;margin-right:.2rem}.smalltable001 .smalltable001tit:after{width:1.09333rem;height:.28rem;content:"";display:inline-block;background:url(../images/insidestyle/smalltableicon003.png) no-repeat;position:static;margin-left:.2rem}.smalltable001 .smalltable001box{border:.16rem solid #fff}.smalltable001 .smalltable001box table{margin:0 auto;width:100%;box-shadow:0 0 .4rem rgba(44,80,179,0.2);border-collapse:collapse;background: #fff;}.smalltable001 .smalltable001box table tr:first-child td{background:#dee6ff}.smalltable001 .smalltable001box table tr:nth-child(even) td{background:#f7f7f7}.smalltable001 .smalltable001box table tr{border:1px solid #000}.smalltable001 .smalltable001box table td{padding:.2rem .13333rem;word-break:break-all;border:1px solid #333;text-align:center;font-size:.37333rem;line-height:.66667rem}.smalltable001 .smalltable001box table td a{color:#6b86cf;text-decoration:underline;position:relative}', // 移动端样式
        htmlString:'<div class="smalltable001"><p class="smalltable001tit">大型煤炭破碎机价格一览表</p><div class="smalltable001box"><table cellpadding="0" cellspacing="0" border="0"><tbody><tr><td>大型煤炭破碎机类型</td><td colspan="2">价格</td></tr><tr><td>颚式破碎机</td><td>2~280万</td><td><a href="#" target="_blank" title="">了解详情</a></td></tr><tr><td>辊式破碎机</td><td>1~30万</td><td><a href="#" target="_blank" title="辊式破碎机">了解详情</a></td></tr><tr><td>锤式破碎机</td><td>1~120万</td><td><span style="white-space:normal;"><a href="#" target="_blank" title="锤式破碎机">了解详情</a></span><br></td></tr><tr><td>反击式破碎机</td><td>8~160万</td><td><a href="#" target="_blank" title="反击式破碎机">了解详情</a></td></tr><tr><td>移动式破碎机</td><td>30~300万</td><td><a href="#" target="_blank" title="移动式破碎机">了解详情</a></td></tr></tbody></table></div></div>'};
}