/*
 * @Author: your name
 * @Date: 2020-01-07 10:45:01
 * @LastEditTime: 2020-01-07 10:45:04
 * @LastEditors: your name
 * @Description: In User Settings Edit
 * @FilePath: \hx-editor\src\components\editorData\tableData\modules\nyb001.js
 */

export function getHtmlData (){
    return{
        type:"", // web(只用于PC端)|wap(只用于移动端)|(PC和移动端通用该值为空)|
        color:'', // 多个颜色用逗号分隔 目前取值项：红色,橙色,蓝色,绿色,棕色,黄色,紫色,粉色,黑色,青色,灰色
        effect:'static', // dynamic(动态)|static(静态)
        align:'left', // left(左对齐)|center(居中对齐)|right(右对齐)        
        style:'icon', // icon(图标)|number(数字)|other(其他)
        class:'smalltable002',// 用来给js使用添加页面内样式使用
        fileName:'nyb002.js', // 该文件的文件名
        styleWebCode:'.smalltable002{clear:both; margin:20px 0px;box-sizing: border-box; background: rgb(1,102,155);position: relative; padding:1px 30px 20px 30px;}.smalltable002:before{content:""; background: rgba(199,237,251,1); position: absolute; left:0px; right: 0px; top:100px;bottom: 0px;border-radius:50px 50px 0 0;}.smalltable002 .smalltable002tit{font-size: 26px !important;color: #fff !important;font-weight: bold;margin: 25px 0 25px !important;text-align: center;padding: 0px !important;background: none !important; position: relative; z-index: 2;}.smalltable002 .smalltable002tit:before,.smalltable002 .smalltable002tit:after{content: "";width:24px; height:19px; display: inline-block;position: static;vertical-align: middle; background: url(../images/insidestyle/smalltableicon004.png) no-repeat;}.smalltable002 .smalltable002tit:before{margin-right: 15px;}.smalltable002 .smalltable002tit:after{ margin-left: 15px;}.smalltable002 .smalltable002box{border: 12px solid #fff; background: #fff; position: relative; z-index: 2;}.smalltable002 .smalltable002box table{margin: 0 auto;width: 100%; background: #fff; border-collapse:collapse;}.smalltable002 .smalltable002box table tr{border: 1px solid rgba(0,86,133,0.3)!important;}.smalltable002 .smalltable002box table tr:first-child td{background:rgb(127,207,237)}.smalltable002 .smalltable002box table tr:nth-child(even) td{background:rgba(199,237,251,0.3)}.smalltable002 .smalltable002box table td{padding: 15px 10px!important;word-break: break-all!important;border: 1px solid rgba(0,86,133,0.3)!important;text-align: center;}.smalltable002 .smalltable002box table td a{color: #6b86cf; text-decoration: underline; position: relative;}', // PC端样式
        styleWapCode:'.smalltable002{clear: both;margin: .26667rem 0rem;box-sizing: border-box;background: rgb(1,102,155);position: relative;padding: .01333rem .2rem .2rem;}.smalltable002:before{content:"";background: rgba(199,237,251,1);position: absolute;left: 0px;right: 0px;top: 1.5rem;bottom: 0px;border-radius: 0.5rem 0.5rem 0rem 0rem;}.smalltable002 .smalltable002tit{font-size:.4rem;margin-bottom:.4rem;color:#fff;font-weight:bold;margin:.33333rem 0rem;text-align:center;color:#fff;background:none;padding:0rem;position:relative;z-index:2}.smalltable002 .smalltable002box{border:.16rem solid #fff;background:#fff;position:relative;z-index:2}.smalltable002 .smalltable002box table{margin:0 auto;width:100%;background:#fff;box-shadow:0 0 .4rem rgba(199,237,251);border-collapse:collapse}.smalltable002 .smalltable002box table tr:first-child td{background:rgb(127,207,237)}.smalltable002 .smalltable002box table tr:nth-child(even) td{background:rgba(199,237,251,0.3)}.smalltable002 .smalltable002box table tr{border:1px solid rgba(0,86,133,0.3)!important}.smalltable002 .smalltable002box table td{padding:.2rem .13333rem;word-break:break-all;border:1px solid rgba(0,86,133,0.3)!important;text-align:center;font-size:.37333rem;line-height:.66667rem}.smalltable002 .smalltable002box table td a{color:#6b86cf;text-decoration:underline;position:relative}', // 移动端样式
        htmlString:'<div class="smalltable002"><p class="smalltable002tit">大型煤炭破碎机价格一览表</p><div class="smalltable002box"><table cellpadding="0" cellspacing="0" border="0"><tbody><tr><td>大型煤炭破碎机类型</td><td colspan="2">价格</td></tr><tr><td>颚式破碎机</td><td>2~280万</td><td><a href="#" target="_blank" title="">了解详情</a></td></tr><tr><td>辊式破碎机</td><td>1~30万</td><td><a href="#" target="_blank" title="辊式破碎机">了解详情</a></td></tr><tr><td>锤式破碎机</td><td>1~120万</td><td><span style="white-space:normal;"><a href="#" target="_blank" title="锤式破碎机">了解详情</a></span><br></td></tr><tr><td>反击式破碎机</td><td>8~160万</td><td><a href="#" target="_blank" title="反击式破碎机">了解详情</a></td></tr><tr><td>移动式破碎机</td><td>30~300万</td><td><a href="#" target="_blank" title="移动式破碎机">了解详情</a></td></tr></tbody></table></div></div>'
    };
}