export function getHtmlData (){
    return{
        type:"", // web(只用于PC端)|wap(只用于移动端)|(PC和移动端通用该值为空)|
        color:'', // 多个颜色用逗号分隔 目前取值项：红色,橙色,蓝色,绿色,棕色,黄色,紫色,粉色,黑色,青色,灰色
        effect:'static', // dynamic(动态)|static(静态)
        align:'center', // left(左对齐)|center(居中对齐)|right(右对齐)        
        style:'other', // icon(图标)|number(数字)|other(其他)
        fileName:'nyb013.js', // 该文件的文件名
        class:'smallbtn013',// 用来给js使用添加页面内样式使用
        styleWebCode:'.smallbtn013{width:560px;height:93px;background:url(../images/insidestyle/smallbtn013.png) left top no-repeat;background-size:100% auto;font-size:0;position:relative;margin:100px auto 0;}.smallbtn013 .smallbtn013-kefu{display:inline-block;vertical-align:top;width:50%;position:relative;text-align:center;}.smallbtn013 .smallbtn013-kefu i{padding-left:46px;margin-top:24px;font-size:14px;color:#262b37;display:block;text-align:left}.smallbtn013 .smallbtn013-kefu a{color:#dd2118;padding-left:46px;font-size:26px;font-weight:bold;margin-top:2px;display:block;text-align:left}.smallbtn013 .smallbtn013-kefu:before{content:"";display:block;width:30px;height:30px;position:absolute;top:36px;left:8px;background:url(../images/insidestyle/smallbtn013-tel.png) left top no-repeat;background-size:100% auto}.smallbtn013 .smallbtn013-zx{display:inline-block;vertical-align:top;width:50%;text-align:center;color:#262b37;font-size:26px;box-sizing:border-box;padding:24px 0 24px 20px;position:relative;cursor:pointer}.smallbtn013 .smallbtn013-zx:before{content:"";display:inline-block;vertical-align:middle;width:34px;height:30px;margin-right:3px;background:url(../images/insidestyle/smallbtn013-kefu.png) left top no-repeat;background-size:100% auto;}.smallbtn013:before{position:absolute;content:"";display:block;width:103px;height:102px;background:url(../images/insidestyle/smallbtn013-kefuimg.png) left top no-repeat;background-size:100% auto;position:absolute;left:36px;top:-100px;}', // PC端样式
        styleWapCode:'.smallbtn013{width:7.46667rem;height:1.24rem;background:url(../images/insidestyle/smallbtn013.png) left top no-repeat;background-size:100% auto;font-size:0;position:relative;margin:1.33333rem auto 0}.smallbtn013 .smallbtn013-kefu{display:inline-block;vertical-align:top;width:50%;position:relative;text-align:center}.smallbtn013 .smallbtn013-kefu i{padding-left:.61333rem;margin-top:.26667rem;font-size:.18667rem;color:#262b37;display:block;text-align:left}.smallbtn013 .smallbtn013-kefu a{color:#dd2118;padding-left:.61333rem;font-size:.34667rem;font-weight:bold;display:block;text-align:left}.smallbtn013 .smallbtn013-kefu:before{content:"";display:block;width:.4rem;height:.4rem;position:absolute;top:.48rem;left:.10667rem;background:url(../images/insidestyle/smallbtn013-tel.png) left top no-repeat;background-size:100% auto}.smallbtn013 .smallbtn013-zx{display:inline-block;vertical-align:top;width:50%;text-align:center;color:#262b37;font-size:.34667rem;box-sizing:border-box;padding:.32rem 0 .32rem .26667rem;position:relative;cursor:pointer}.smallbtn013 .smallbtn013-zx:before{content:"";display:inline-block;vertical-align:middle;width:.45333rem;height:.4rem;margin-right:.04rem;background:url(../images/insidestyle/smallbtn013-kefu.png) left top no-repeat;background-size:100% auto;}.smallbtn013:before{position:absolute;content:"";display:block;width:1.37333rem;height:1.36rem;background:url(../images/insidestyle/smallbtn013-kefuimg.png) left top no-repeat;background-size:100% auto;position:absolute;left:.48rem;top:-1.33333rem}', // 移动端样式
        htmlString:'<div class="smallbtn013"><div class="smallbtn013-kefu"><i>免费咨询热线</i><a href="tel:0371-67772626">0371-67772626</a></div><a href="javascript:;" class="smallbtn013-zx">立即咨询</a></div>'
    };
}